#!/usr/bin/env ruby

require 'rubygems'
require 'bundler'

Bundler.require

root = ::File.dirname(__FILE__)

libs = []
libs << "-r irb/completion"
libs << "-r ./application"
exec "irb #{libs.join(" ")} --simple-prompt"

