source 'http://rubygems.org'

gem 'sinatra', '~> 1.3.1'
gem 'shotgun'
gem 'yajl-ruby'
gem 'curb'
gem 'capistrano'
gem 'sass'
gem 'haml'
gem 'mongoid', '2.0.0'
gem 'bson_ext'
gem 'twitter'
gem 'whenever'
gem 'rake'
